# Generated by Django 2.2.7 on 2020-05-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='userIden',
            new_name='user_iden',
        ),
    ]
