# Generated by Django 2.2.7 on 2020-05-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20200507_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='details',
            name='image',
        ),
        migrations.AddField(
            model_name='details',
            name='picture',
            field=models.ImageField(null=True, upload_to='profilepics/'),
        ),
    ]
