# Generated by Django 2.2.7 on 2020-05-07 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_auto_20200507_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='user_iden',
            new_name='user',
        ),
    ]
