# Generated by Django 2.2.7 on 2020-05-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_auto_20200507_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
